### ISSUE TITLE
[Anregung] Aktivierungsfarbe

### ISSUE THREAD

**Issue by Sacred-Shadow** [ZhooL/FS22_EnhancedVehicle#1]
Die Farbe vom Snap sollte getauscht werden.
Aktuell ist ja inaktiv grün und aktiv rot.

Umgedreht ist es eigentlich logischer ... wenn der Snap-Mode aus ist, passt das rot besser.

**Comment by ZhooL** [comment]
Hmmm hmm für mich war rot die Wahl, da es für mich bedeutet: Achtung - ist aktiv. Grün ist einfach nur der aktuelle Richtung des Fahrzeugs wie auch auf der Minimap.

**Comment by Tensuko** [comment]
Aus der Sicht, ja.

Aber normal würde ich auch rot für inaktiv und grün für aktiv wählen.
Bei sowas denke ich ehrlich gesagt nicht an 'achtung - aktiv' :)

**Comment by Sacred-Shadow** [comment]
Schauen wir mal aufs Auto ... da ist grün idR. auch immer die Farbe für aktive Assistenten (Spurhalte, Abstand usw.). 
IdR. ist halt "grün" immer so die Leuchte für "aktiv" und alles in Ordnung.

Rot immer für Warnung.
Weiß oder garnicht leuchtend für ist aus/inaktiv.

**Comment by Tensuko** [comment]
@ZhooL 
was wäre wenn du das in der config XML konfigurierbar machst ?

` ...
snap active = Y
snap inactive = X`

**Comment by ZhooL** [comment]
Ich mach das hier mal zu, Die Farben sind inzw. angepasst und ein paar weitere Farben kann man sich in der XML anpassen.
