### ISSUE TITLE
Hotlines aktivieren

### ISSUE THREAD

**Issue by potcoavaandrei** [ZhooL/FS22_EnhancedVehicle#10]
Hi ... I Have a Problem ... I Can't Activate the direction of travel view .. I Can't Activate This Option!
I Can Only Activate Shift + Home | toggle damage / fuel display on / off.
The Reason There Are 2 Options With The Same Activation Keys!
A Help Please! Thanks

Shift+Home | toggle damage/fuel display on/off

Shift+Home | turn on/off visualization of driving direction (Helplines/Hilfslinien)

**Comment by ZhooL** [comment]
Shift+Home for toggle dmg display is from a previous version and the engine does not adapt the keybindings automatically. Go to key binding and configure toogle dmg display to ctrl+/ (numpad), than rebind helplines to shift+home
