### ISSUE TITLE
issue with right ctrl end 

### ISSUE THREAD

**Issue by CD1982** [ZhooL/FS22_EnhancedVehicle#101]
so  i have tried all versions and when pressing the ctrl button on the right side of the keyboard and using the end key.. 
i always getting a message saying  the working width was recalulated ...  
and when pressing ctrl num delete key  it tells me track assistant  not enabled   

ive watched youtube videos on how to set this up for fs 22 and i cant get it to work  with the built in gps 
i can get lines showing up by pressing the ctrl 3 key but thats it i can not get the little steering wheel to trun green  etc 

the lockers work fine

**Comment by Greencoffee546** [comment]
Check keybinds

**Comment by ZhooL** [comment]
Its most probably a conflict with other mods keybindings
