### ISSUE TITLE
LUA Error at the Beginn of the Game

### ISSUE THREAD

**Issue by TheKingOfHarts** [ZhooL/FS22_EnhancedVehicle#102]
Until Yesterday i have no Errors in the Game with the Mod but since yesterday i have this Errror at the Beginn of the Game, FarmingSimulator2022/mods/FS22_EnhancedVehicle/FS22_EnhancedVehicle.lua:1288: attempt to index field 'ui_hud' (a nil value)
2022-06-20 06:46 Error: Running LUA method 'draw'. I can do Nothing and must End the Game, without the Enhanced Vehicle Mod the Game runs normal.

**Comment by ZhooL** [comment]
Hi, can you please provide the complete log.txt file.

**Comment by TheKingOfHarts** [comment]
[log.txt](https://github.com/ZhooL/FS22_EnhancedVehicle/files/8942472/log.txt)

**Comment by TheKingOfHarts** [comment]
With another Save game there is no Problem, I think my save game is broken a soon as I enter a Vehicle the Error start

**Comment by jason0611** [comment]
I would at least give it a try without FS22_DynamicFieldPrices, because it throws up a (severe) error message in your log.

**Comment by TheKingOfHarts** [comment]
ok thanks, it works again. I have clean up my Mods and now the Game runs

**Comment by ZhooL** [comment]
Thank you for investigating and supporting 👍
