### ISSUE TITLE
Question about adding new functionality

### ISSUE THREAD

**Issue by VyaDobra** [ZhooL/FS22_EnhancedVehicle#103]
Hello, 

i'd like to add a visual indicator (like your parking brake on / off) for the implement state limit to field/allow create field.
Would you be so kind and help me achieve this goal?

**Comment by ZhooL** [comment]
Hi, I'm sorry, but no new features are planned to be implemented.

**Comment by VyaDobra** [comment]
Good evening, would you mind if i try to add that functionality myself?

**Comment by ZhooL** [comment]
Sure - go for it. EV wouldn't be on GitHub if I don't want people to be able to contribute to it.
