### ISSUE TITLE
Dedicated rooro popping up

### ISSUE THREAD

**Issue by MrMazzony** [ZhooL/FS22_EnhancedVehicle#105]
`2022-07-25 20:57 Error: Running LUA method 'packetReceived'.
game/mods/FS22_EnhancedVehicle/FS22_EnhancedVehicle.lua:1330: attempt to index field 'ui_hud' (a nil value)
`
Something to address, or just our modconflicts?

**Comment by ZhooL** [comment]
Mod conflict. Check out https://github.com/ZhooL/FS22_EnhancedVehicle/issues/102 - maybe it's ther same issue for you.
