### ISSUE TITLE
Add wheel slip indicator and possibly diffirent fuel usage depending on drive state/type

### ISSUE THREAD

**Issue by MacGregor129** [ZhooL/FS22_EnhancedVehicle#107]
With control of differentials. It would be nice to have option to see how much wheel slip you get as a result indication when engage 4wd and/or diff lock.

Also since currently there is no reason in game to not drive 4wd, fully locked. It would be nice idea (if possible) to have different fuel economy depending if 4wd is engaged or not etc.

**Comment by ZhooL** [comment]
It's not planned to implement additional features.
