### ISSUE TITLE
Front & Rear controls not working

### ISSUE THREAD

**Issue by djtwist** [ZhooL/FS22_EnhancedVehicle#112]
Looks like this is on Giants side and one of their updates broke this feature. I have been running the original version for FS22 when you first released it. I finally updated to your latest and started using it today and found out that my front and rear raise and lower no longer works. I tried remapping my joystick with no success. 
I then tried the original version I had from last year and again it does not work with tells me that one of the giants updates has killed this feature. 

This is my favorite feature of your mod to be honest.

**Comment by LunchPinnar** [comment]
Same running a plow front and back is a pain again :))
