### ISSUE TITLE
ShowKeysInHelpMenu has no function

### ISSUE THREAD

**Issue by AN-Vyper007** [ZhooL/FS22_EnhancedVehicle#113]
Hello, i am unable to hide the keymapping in F1-Help Menu.
i configured  ".\Documents\My Games\FarmingSimulator2022\modSettings\FS22_EnhancedVehicle\FS22_EnhancedVehicle_v1.xml": 

misc showKeysInHelpMenu="false" soundIsOn="true"

but no change. Fix Possible?

**Comment by ZhooL** [comment]
I also noted that behavior of the game engine. It simply does not work as expected. Guess its just another flaw in the Giants Engine
