### ISSUE TITLE
Mod Tractor does not have the correct mass in MP

### ISSUE THREAD

**Issue by MeRida2104** [ZhooL/FS22_EnhancedVehicle#115]
Hello @ZhooL,

we use the following modtractor in multiplayer:

https://sharemods.com/i77peqx476dd/FS22_JohnDeere_8R_2009.zip.html (by Dince)

We have noticed that the total mass of the tractor in MP is only 5.1 tons. When I call the same savegame in SP, the total mass of the tractor is 14.9 tons (which is correct). As a result, the tractor starts to "float" with large trailer loads. 

Is there any way to change this? Would appreciate a tip/hint from you.

Here are two screenshots that describe the problem visually:

![image](https://user-images.githubusercontent.com/96819380/220316693-8f315282-b590-4c11-89fc-c105a81f8b9b.png)

![image](https://user-images.githubusercontent.com/96819380/220316963-a6071fdb-a3d8-4a4f-acd0-436115d0597c.png)

Best regards
MeRida

**Comment by ZhooL** [comment]
Please read the documentation. Some things do not work in MP due to limitations of the game engine.
