### ISSUE TITLE
Track Assistant, Centerline

### ISSUE THREAD

**Issue by Gizmer67** [ZhooL/FS22_EnhancedVehicle#120]
Is it possible to change the color of the center line of the guide lines (Track Assistant), for example blue or some other contrasting color than the outer lines?
Sometimes I take the wrong line when I have to start my job because that the colors are so similar.

Otherwise, thanks for a great app.

**Comment by ZhooL** [comment]
Check out the config file in "My Games/FarmingSimulator2022/modSettings/FS22_EnhancedVehicle/FS22_EnhancedVehicle_v1.xml"

        <colorAttachmentSideLine blue="0.000000" green="0.000000" red="0.392157"/>
        <colorVehicleMiddleLine blue="0.298039" green="0.298039" red="0.298039"/>
        <colorVehicleSideLine blue="0.000000" green="0.000000" red="1.000000"/>

**Comment by Gizmer67** [comment]
Thank you! :)
