### ISSUE TITLE
Sperrdifferentiale sind nach dem Spielstart aus, obwohl sie als an abgespeichert wurden

### ISSUE THREAD

**Issue by 112TEC-Chris** [ZhooL/FS22_EnhancedVehicle#17]
Hallo,
wenn ich die Sperrdifferentiale einschalte und damit dann das Spiel abspeichere wird auch das folgende in die vehicles.xml im savegame geschrieben:
`        <FS22_EnhancedVehicle>
            <EnhancedVehicle frontDiffIsOn="true" backDiffIsOn="true" driveMode="1"/>
        </FS22_EnhancedVehicle>`
Wenn ich dann das Spiel neu starte sind sie aber trotzdem aus.

**Comment by ZhooL** [comment]
Danke für's Melden. Wird in der nächsten Version gefixt sein.
