### ISSUE TITLE
Schadensanzeige

### ISSUE THREAD

**Issue by BLACKOUT-Z0ck3R** [ZhooL/FS22_EnhancedVehicle#2]
Hallo und erstmal danke, dass der Mod in den 22er geholt wurde :)
Leider zeigt die Schadensanzeige momentan nicht den Schaden des Fahrzeugs/Anbaugeräts an, sondern glaube die Prozente der Lackabnutzung :D
Wär schön, wenn das gefixt wird.
LG Patrick

**Comment by ZhooL** [comment]
Jau hab was dazu in der 0.9.5.0 geändert, aber es ist wie immer ein Drama im Multiplayer mit den Werten. Die Engine gibt nur irgendwas zurück, was meistens nicht richtig stimmt..

**Comment by ZhooL** [comment]
In der 0.9.6.0 werden beide Werte (Schaden, Lack) separat angezeigt.
