### ISSUE TITLE
Fehler auf dem MP

### ISSUE THREAD

**Issue by GulliGriff** [ZhooL/FS22_EnhancedVehicle#20]
Erst mal vielen Dank für Dein Mod, jetzt brauche ich keinen extra Mod mehr für GPS.. 
Allerdings habe ich auf dem Server ein Problemchen festgestellt...
Was auch immer das bedeuten soll, aber da scheint es ein Problem mit der Schriftgröße zu geben.
kannst Du da bitte mal schauen, hab dir mal die log angehangen...
[log_server.txt](https://github.com/ZhooL/FS22_EnhancedVehicle/files/7696874/log_server.txt)
?
Danke schon mal :)

Edit: die Mods von Happy Looser hatte ich auch mal deaktiviert (und entfernt), aber der Schrift-Fehler war noch immer da. Ich glaube mich erinnern zu können, dass es seit ich Dein Mod drauf habe ist.

**Comment by ZhooL** [comment]
Danke. ich schau es mir mal an

**Comment by ZhooL** [comment]
Die Meldungen sind vom Spiel selbst und nicht vom EV Mod. Es wurde auch von anderen Leuten schon an Giants gemeldet. Selbst wenn du sämtliche Mods entfernst erscheinen diese Meldungen beim Starten des Dedi-Servers.

**Comment by GulliGriff** [comment]
Entschuldige, das habe ich nicht getestet :(
