### ISSUE TITLE
Removing snap direction feature

### ISSUE THREAD

**Issue by majkl36** [ZhooL/FS22_EnhancedVehicle#21]
Hi,
a this time there are at least two lane guidance/snap direction mods.

https://github.com/Mogli12/VehicleControlAddon
https://www.farming-simulator.com/mod.php?mod_id=228522

Can you please remove that feature or make separate version without it.

**Comment by ZhooL** [comment]
Why should I? I do this because of fun and learning stuff. If you don't like it -> don't use this mod. Or better: RTFM and disable the snap/track feature in the config dialog.
