### ISSUE TITLE
SNAP_INC(DEC)_TRACK

### ISSUE THREAD

**Issue by Kynuska** [ZhooL/FS22_EnhancedVehicle#22]
Hello.
Please tell me how this feature works. I tried it in the game and found no effect other than a changing number. I don't know how to translate it.
Thanks.
Kynuska

**Comment by ZhooL** [comment]
Hi :-)

1. position your vehicle with an attachment somewhere ideally at a field border
2. press rctrl+numpad 1 to calculate and enable track layout. a lot of visual lines will appear
3. above the speedometer you see something like "# 0   +1" (you're in track 0 and the turnover number is +1)
4. press rctrl+end to snap your vehicle to the current track #0 and drive maybe a bit. vehicle will stay in the track
5. press rctrl+pos1 to turn to the next track. Display will change to "# 1   +1"
6. press drive forward and your vehicle will turn around and position itsself in track # 1 
7. if you want to to turn "in the other track direction" use rctrl+numpad 4/6 to change the turnover number from +1 to -1
8. if you set the turnover number to for example +3 the vehicle will skip two lines when turning and position itsself in the third next track

It's even hard for me to explain this in english... I guess I might miss some technical wording for all this track and lanes and turn around and snap this and that ;-)

Thank you for your support.
