### ISSUE TITLE
Wendeschaltung

### ISSUE THREAD

**Issue by Bandesss** [ZhooL/FS22_EnhancedVehicle#24]
Hallo Zhool, wird es wieder die Wendeschaltung geben ?
Danke für deinen Mod

**Comment by ZhooL** [comment]
Hi, nein wird es nicht geben, da so etwas bereits im LS22 fest eingebaut ist. Vielleicht solltest du dir mal anschauen, was das Spiel von Haus aus schon kann ;-)

**Comment by Bandesss** [comment]
Schade deins war besser 
Danke für die Info
