### ISSUE TITLE
Kraftstoffverbrauch

### ISSUE THREAD

**Issue by JCB2904** [ZhooL/FS22_EnhancedVehicle#25]
Moin Moin,

kurz Frage: aufm Server funktioniert die Anzeige vom Kraftstoffverbraucht nicht, im Multiplayer ja.

Ist das so richtig? oder muss man auf Server was einstellen?

Gruß Jan

**Comment by ZhooL** [comment]
Steht in der readme: "In multiplayer games, all clients, except the host, won't display the fuel usage rate and engine temperature correctly"

Auf Deutsch: Die Werte stehen im Multiplayer nicht zur Verfügung.
