### ISSUE TITLE
Kein Gerät mit Arbeitsbreite gefunden

### ISSUE THREAD

**Issue by GulliGriff** [ZhooL/FS22_EnhancedVehicle#27]
Hallöchen, ich habe gerade 2 Dinge gefunden auf dem MP..
- Bei Güllefässern erkennt er leider die Anbaugeräte nicht als Gerät mit Arbeitsbreite
- der Tempomat wird leider nicht abgeschaltet (wenden klappt)
Noch ne Frage hinterher.. 
- wäre es möglich, dass er beim Wenden die Geräte anhebt bzw. abschaltet (bei ner Spritze bspw.)?
- wäre es möglich auch Einfluss auf die Arbeitsbreite zu nehmen oder auch generell eine einzustellen (wäre hilfreich beim Häcksler abfahren)?
Ansonsten, mega was Du da bisher gezaubert hast. Also bei uns kommt nix anderes mehr drauf... VCA war mir eh immer viel zu viel kram dabei... Danke für für Deine Arbeit und den Mod !!!!

**Comment by ZhooL** [comment]
Danke für's Feedback. Ich schau mir die Punkte die nächsten Tage an.

**Comment by ZhooL** [comment]
* Güllefässer wird in 0.9.9.7 gefixt sein
* Arbeitsbreite wird man ab 0.9.9.7 verringern/erhöhen können, aber als Abfahrer hast du eigentlich nichts "mit einer Arbeitsbreite" angehängt und wirst den Trackassistant gar nicht einschalten können... ich laß mir dafür mal was einfallen

**Comment by GulliGriff** [comment]
das wäre toll, meine Jungs haben immer gern beim abfahren die breite des Häckslers eingestellt damit die dann immer schön gleich in die richtige spur daneben fahren konnten. ich brauche nicht aber falls du bock hast..

**Comment by Kotlett** [comment]
Ladewagen werden auch nicht mit Arbeitsbreite erkannt.

**Comment by ZhooL** [comment]
Version 1.0.1.0 erkennt nun auch die Arbeitsbreiten von Ladewagen, Ballenpressen, etc.
