### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Ty4kaKou** [ZhooL/FS22_EnhancedVehicle#28]
I translated it into Russian. Please add it.
Google Disc -  [click](https://drive.google.com/file/d/1ete3fBoMJGsEWtXx2uURtqCtYED_pRIM/view?usp=sharing)
`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<l10n>
  <translationContributors>Ty4kaKou</translationContributors>

  <texts>
    <text name="input_FS22_EnhancedVehicle_SNAP_ONOFF"      text="EV: Привязать текущее направление"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_ONOFF2"     text="EV: Привязать предыдущее направление"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_REVERSE"    text="EV: Обратное направление привязки (180°)"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_LINES"      text="EV: Вспомогательные линии вкл/выкл"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC1"       text="EV: Увеличить направление привязки на 1°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC1"       text="EV: Уменьшить направление привязки на 1°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC2"       text="EV: Увеличить направление привязки на 45°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC2"       text="EV: Уменьшить направление привязки на 45°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC3"       text="EV: Увеличить направление привязки на 90°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC3"       text="EV: Уменьшить направление привязки на 90°"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_GRID_ONOFF" text="EV: Вкл/выкл сетку"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_GRID_RESET" text="EV: Сбросить сетку"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC_TRACK"  text="EV: Увеличить количество поворотных линий"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC_TRACK"  text="EV: Уменьшить количество поворотных линий"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC_TRACKP" text="EV: Сдвинуть линию вправо"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC_TRACKP" text="EV: Сдвинуть линию влево"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_INC_TRACKO" text="EV: Сдвинуть линию смещения вправо"/>
    <text name="input_FS22_EnhancedVehicle_SNAP_DEC_TRACKO" text="EV: Сдвинуть линию смещения влево"/>
    <text name="input_FS22_EnhancedVehicle_FD"              text="EV: Вкл/выкл блокировку переднего дифференциала"/>
    <text name="input_FS22_EnhancedVehicle_RD"              text="EV: Вкл/выкл блокировку заднего дифференциала"/>
    <text name="input_FS22_EnhancedVehicle_BD"              text="EV: Вкл/выкл блокировку переднего и заднего дифференциала"/>
    <text name="input_FS22_EnhancedVehicle_DM"              text="EV: Изменить режим привода на колесах"/>
    <text name="input_FS22_EnhancedVehicle_AJ_REAR_UPDOWN"  text="EV: Задняя гидравлика поднять/опустить"/>
    <text name="input_FS22_EnhancedVehicle_AJ_REAR_ONOFF"   text="EV: Задняя гидравлика вкл/выкл"/>
    <text name="input_FS22_EnhancedVehicle_AJ_FRONT_UPDOWN" text="EV: Передняя гидравлика поднять/опустить"/>
    <text name="input_FS22_EnhancedVehicle_AJ_FRONT_ONOFF"  text="EV: Передняя гидравлика вкл/выкл"/>
    <text name="input_FS22_EnhancedVehicle_MENU"            text="EV: Открыть меню конфигурации"/>

    <text name="ui_FS22_EnhancedVehicle_on"  text="Вкл"/>
    <text name="ui_FS22_EnhancedVehicle_off" text="Выкл"/>

    <text name="ui_FS22_EnhancedVehicle_sectionGlobalFunctions" text="Глобальные настройки"/>
    <text name="ui_FS22_EnhancedVehicle_sectionHUD"             text="HUD настройки"/>
    <text name="ui_FS22_EnhancedVehicle_sectionSnapSettings"    text="Настройки помощника"/>

    <text name="ui_FS22_EnhancedVehicle_resetConfigButton"  text="Сбросить настройки мода"/>
    <text name="ui_FS22_EnhancedVehicle_resetConfigTitle"   text="Сбросить конфигурацию файла"/>
    <text name="ui_FS22_EnhancedVehicle_resetConfigTT"      text="ВНИМАНИЕ: Это вернет все настройки этого мода по умолчанию!"/>
    <text name="ui_FS22_EnhancedVehicle_reloadConfigButton" text="Перезагрузить конфигурацию мода (XML)"/>
    <text name="ui_FS22_EnhancedVehicle_reloadConfigTitle"  text="Перезагрузить файл конфигурации"/>
    <text name="ui_FS22_EnhancedVehicle_reloadConfigTT"     text="Перезагрузить файл конфигурации с диска. Необходимо после внесения изменений в XML-файл вручную."/>

    <text name="ui_FS22_EnhancedVehicle_snapTitle"      text="Помощник"/>
    <text name="ui_FS22_EnhancedVehicle_snapTT"         text="Вкл/выкл глобальные функции помошника"/>
    <text name="ui_FS22_EnhancedVehicle_diffTitle"      text="Блокировка дифференциала"/>
    <text name="ui_FS22_EnhancedVehicle_diffTT"         text="Вкл/выкл глобальные функции блокировки дифференциала"/>
    <text name="ui_FS22_EnhancedVehicle_hydraulicTitle" text="Улучшенное гидравлическое управление"/>
    <text name="ui_FS22_EnhancedVehicle_hydraulicTT"    text="Вкл/выкл глобальные функции управления гидравликой"/>

    <text name="ui_FS22_EnhancedVehicle_HUDdiffTitle"   text="HUD: Блокировка дифференциала"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdiffTT"      text="Вкл/выкл отображение на дисплее блокировки дифференциала"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdmgTitle"    text="HUD: Количество повреждений"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdmgTT"       text="Вкл/выкл отображение на дисплее количество повреждений"/>
    <text name="ui_FS22_EnhancedVehicle_HUDfuelTitle"   text="HUD: Уровень топлива"/>
    <text name="ui_FS22_EnhancedVehicle_HUDfuelTT"      text="Вкл/выкл отображение на дисплее уровень топлива"/>
    <text name="ui_FS22_EnhancedVehicle_HUDsnapTitle"   text="HUD: Помощник"/>
    <text name="ui_FS22_EnhancedVehicle_HUDsnapTT"      text="Вкл/выкл отображение на дисплее помощник"/>
    <text name="ui_FS22_EnhancedVehicle_HUDrpmTitle"    text="HUD: Об/мин"/>
    <text name="ui_FS22_EnhancedVehicle_HUDrpmTT"       text="Вкл/выкл отображение на дисплее Об/мин"/>
    <text name="ui_FS22_EnhancedVehicle_HUDtempTitle"   text="HUD: Температура двигателя"/>
    <text name="ui_FS22_EnhancedVehicle_HUDtempTT"      text="Вкл/выкл отображение на дисплее температура двигателя"/>
    <text name="ui_FS22_EnhancedVehicle_HUDmiscTitle"   text="HUD: Разные значения (вес)"/>
    <text name="ui_FS22_EnhancedVehicle_HUDmiscTT"      text="Вкл/выкл отображение на дисплее разные значения (вес)"/>

    <text name="ui_FS22_EnhancedVehicle_HUDdmgAmountLeftTitle" text="HUD: Режим значений урона"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdmgAmountLeftTT"    text="Показывать значения повреждений в '% осталось' а не в '% повреждения'"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdmgAmountLeftO1"    text="% осталось"/>
    <text name="ui_FS22_EnhancedVehicle_HUDdmgAmountLeftO2"    text="% повреждения"/>

    <text name="ui_FS22_EnhancedVehicle_snapSettingsAngleTitle" text="Привязка к углу"/>
    <text name="ui_FS22_EnhancedVehicle_snapSettingsAngleTT"    text="Определяет с каким шагом включается направление движения(1°-90°)"/>

    <text name="global_FS22_EnhancedVehicle_snapNotEnabled" text="Помощник направления не включен."/>
    <text name="global_FS22_EnhancedVehicle_snapNoImplement" text="Не нашел устройства с шириной захвата."/>

  </texts>
</l10n>`

**Comment by ZhooL** [comment]
Thanks for your contribution. Will be included in the next release.
