### ISSUE TITLE
[Anregung] Grafische Anpassung

### ISSUE THREAD

**Issue by Sacred-Shadow** [ZhooL/FS22_EnhancedVehicle#3]
Die HUD Elemente im LS22 sind abgerundet. 
Wär iwie cool, wenn die beiden Anzeigen sich dem bissel anschließen würden.

Denn wirkt der Stylbruch zu den anderen Anzeigen nicht so arg.
Evtl. in dem Zug auch das Hellblau von Giants als Schriftfarbe nehmen?

**Comment by ZhooL** [comment]
Steht auf der ToDo, aber mit geringer Prio. "rund" ist immer nerviger als "eckig" zu implementieren ;-)

**Comment by ZhooL** [comment]
0.9.9.8 sollte dieses Thema weitestgehend erledigen ;-)
