### ISSUE TITLE
Mod overlay with VCA

### ISSUE THREAD

**Issue by Markus33-ITA** [ZhooL/FS22_EnhancedVehicle#33]
Hi. The mod overlaps with vehicle control addon. I attach screen [https://i.imgur.com/ziCbIay.png](https://i.imgur.com/ziCbIay.png)

**Comment by ZhooL** [comment]
Yes, and to be honest: I don't care. EV and VCA do not work together. Unfortunately, you have to decide between one of them.

**Comment by Markus33-ITA** [comment]
I'm testing your mod i enjoy it. The number for each guide is nice.
Difficult choice.
Thanks for the reply
