### ISSUE TITLE
Einer für alle :( 0.9.9.9

### ISSUE THREAD

**Issue by GulliGriff** [ZhooL/FS22_EnhancedVehicle#34]
Hallöchen, das neue Layout (0.9.9.9) sieht echt nice aus, allerdings gelten nun die "GPS"-Einstellungen die der erste der diese aktiv stellt für alle anderen :( im MP
Kannst Du da bitte noch mal schauen. Habe jetzt erst mal wieder die 0.9.9.7

**Comment by ZhooL** [comment]
Kannst du das etwas genauer beschreiben? An der Funktionalität hat sich eigentlich nichts geändert... es wurde nur an der Anzeige gebastelt...

**Comment by GulliGriff** [comment]
wenn jemand im MP GPS einstellt und aktiviert haben alle anderen die gleiche Anzeige wie der, der eben GPS aktiviert hat...
Somit kann keiner GPS nutzen, weil ja das eigene nicht zu sehen ist. Da ich aber selber nicht auf dem Feld war, weiss ich nicht, ob auch die Linien am Boden die von anderen oder doch meine eigenen waren.
Ich schmeiss dem Mod noch mal drauf und meld mich gleich noch mal...

**Comment by GulliGriff** [comment]
So.. immer der der zuletzt in ein Fahrzeug steigt, dessen Sachen werden bei allen angezeigt. Das betrifft alle Anzeigen und Zustände. Steigt dieser aus verschwinden auch bei allen die Anzeigen.

**Comment by ZhooL** [comment]
Ich schau mir das mal an.. hab schon eine Idee was es sein kann

**Comment by GulliGriff** [comment]
brauchst du einen Server zum testen?

**Comment by ZhooL** [comment]
Danke, aber ich habe alles zum Multiplayer testen

**Comment by GulliGriff** [comment]
![20211223230707_1](https://user-images.githubusercontent.com/59224815/147295194-c9a037a0-46c4-49c0-9d5d-63b876672882.jpg)
so sieht das bei mir aus.

Update: scheint egal zu sein wer aussteigt, die anderen haben dann jedenfalls keine anzeigen mehr

**Comment by GulliGriff** [comment]
![20211223231426_1](https://user-images.githubusercontent.com/59224815/147295662-03ba10ae-3589-49d4-9e67-75430871da3e.jpg)

Was mir gerade aufgefallen ist, die Temperaturanzeige geht wohl im MP nicht...
Wie zu sehen, alles weg, nachdem er ausgestiegen ist. egal wer jetzt einsteigt, dessen Anzeige ist dann zu sehen...

**Comment by GulliGriff** [comment]
![20211223231910_1](https://user-images.githubusercontent.com/59224815/147295948-be5836c9-da63-4d45-b836-dc261c5232de.jpg)

irgendwie fehlt hier glaub was...

Update: es ist hier auch nichts mehr anklickbar

**Comment by GulliGriff** [comment]
![20211223232233_1](https://user-images.githubusercontent.com/59224815/147296113-68243d46-5474-46c2-bad9-9b8ac6a4edde.jpg)

hat die log gerade ausgespuckt:

2021-12-23 23:18 Error: Running LUA method 'update'.
C:/Users/ralfs/Documents/My Games/FarmingSimulator2022/mods/FS22_EnhancedVehicle/ui/FS22_EnhancedVehicle_UI.lua:121: attempt to index field 'vehicle' (a nil value)
2021-12-23 23:19 Error: Running LUA method 'update'.
C:/Users/ralfs/Documents/My Games/FarmingSimulator2022/mods/FS22_EnhancedVehicle/ui/FS22_EnhancedVehicle_UI.lua:121: attempt to index field 'vehicle' (a nil value)
2021-12-23 23:20 Error: Running LUA method 'update'.
C:/Users/ralfs/Documents/My Games/FarmingSimulator2022/mods/FS22_EnhancedVehicle/ui/FS22_EnhancedVehicle_UI.lua:121: attempt to index field 'vehicle' (a nil value)
2021-12-23 23:21 Error: Running LUA method 'update'.
C:/Users/ralfs/Documents/My Games/FarmingSimulator2022/mods/FS22_EnhancedVehicle/ui/FS22_EnhancedVehicle_UI.lua:121: attempt to index field 'vehicle' (a nil value)

------------------------------------------------------------------------------------------------
ist bestimmt nur ein mal, hab mehrfach die Settings aufgerufen

**Comment by ZhooL** [comment]
Testet mal 1.0.0.0-rc1

**Comment by GulliGriff** [comment]
supi, danke. scheint so zu funktionieren wie es muss.
vielen Dank und schöne Weihnachten wünschen Dir mein ganzes Team und ich natürlich auch :)
