### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by leo32128fs** [ZhooL/FS22_EnhancedVehicle#36]
Hi, good night, good job with this mod, I would like to know if there is a way to go back to the option to increase the icons and numbers on the hud because I use a small monitor and I hardly see them, if there is, I would be very grateful, merry christmas

**Comment by ZhooL** [comment]
I'm sorry, but that option is no longer available. The HUD is now positioned, aligned and sized automatically to the game original HUD. The only option to make it "bigger" is to use the games global option to resize the HUD.

But I plan to make an option to move the damage/fuel numbers to the upper-right of the screen with a background again and maybe resizeable.

**Comment by ZhooL** [comment]
check out 1.0.0.0-rc2 ;-)
