### ISSUE TITLE
Lob an den ersteller des Mods

### ISSUE THREAD

**Issue by FarmerMike87** [ZhooL/FS22_EnhancedVehicle#37]
Hallo ich wollte mich mal bedanken, für diesen mega geilen Mod. 
Ich bin absolut zufrieden, und das Spielen macht damit Mega Spaß.

Eine Anregung hätte ich allerdings, was mir in dem Mod etwas fehlt ist das sich die Kamera automatisch um 180 grad dreht wenn ich rückwärts fahre. Im VCA ist diese Funktion ja eingebaut, wäre es den eventuell möglich diesen Mod damit zu ergänzen ?? 
Hätte den Vorteil das ich und viele andere nicht beide Mods mit mehr oder weniger den selben Funktionen nutzen müssten. Zum anderen würde man dann Modkonflikte auch wieder eingrenzen.

Ist natürlich nur ein Vorschlag/Wunsch meinerseits was letztendlich in den Mod gescriptet wird entscheidet natürlich der Erbauer dieses Kunstwerks.

Wünsche in diesem Sinne noch einen schönen 2. Weihnachtsfeiertag und einen Guten Rutsch ins neue Jahr.

LG Mike

**Comment by ZhooL** [comment]
Danke schön :-) Ich habe allerdings nicht geplant, dieses Kamerafeature einzubauen. Ich wurde schon damals beim LS19 danach gefragt, habe mich aber stets dagegen entschieden. Ich wollte beim EV nie mit der Kamera rumspielen.

**Comment by FarmerMike87** [comment]
Danke für die antwort aber dann muss ich mich wohl für den VCA entscheiden, aber okay ich werde es überleben
