### ISSUE TITLE
Wollte einfach mal Danke sagen...

### ISSUE THREAD

**Issue by rondo24xx** [ZhooL/FS22_EnhancedVehicle#4]
Moinsen,...

auf diesem Weg mal einfach nur ein Dankeschön für die MOD. Viele vermisste Funktionen zur Bedienung der Geräte sind jetzt somit im LS22 wieder gegeben und das so kurz nach Release.... Top 

Vielen Dank

**Comment by scud1984** [comment]
Da möchte ich mich gern anschließen.

Danke für deine tolle und schnelle Arbeit :)

**Comment by timmi4026** [comment]
Von mir auch einen Riesen Dank für den Mod, hab auch mal eine Frage, mir ist aufgefallen das die 180 Grad Wende in der neuen Version 10 Meter Radius hat, vorher waren es 26 Meter. Ist es möglich das einstellbar zu machen z.b. Wende in 12,15,18m ? Das deckt dann quasi einige Anbauteile ab. Vllt noch links oder rechts herum wenden. 

LG. Timmi

**Comment by CODEYXone** [comment]
Danke auch von mir. Der Mod macht das Spiel um einiges besser! :)

**Comment by ZhooL** [comment]
@timmi4026 Der Radius ist reiner Zufall. Er ist nur kleiner geworden, weil in den neueren Versionen des Mods die Lenkmethode anders ist und er schneller rum kommt. Ich habe nicht vor, feste Radien o.ä. einzubauen. Es geht rein ums Spurhalten, nicht um Wenden.

**Comment by elninoE2** [comment]
Ich habe mich extra und zunächst nur registriert, um mich hier anzuschließen! Vielen, vielen Dank für das GPS-Feature. Die anderen Features schätze ich schon länger durch vorher LS Editionen, aber die Implementierung zum Spurhalten sorgt für eine riesengroße Menge mehr Entspannung in LS22. Nochmals: vielen Dank! :)

**Comment by Bobster82** [comment]
I think this is the thanks topic ;)
Thanks for this mod, I almost wrote the "gps" function for myself, but you have it in your mod. No need for me to struggle haha!
I really like it, its simpel and works great! Im looking forward to your updates
