### ISSUE TITLE
Request for additional headland settings 

### ISSUE THREAD

**Issue by kurguplu** [ZhooL/FS22_EnhancedVehicle#43]
Hi,

I am using headland and snapping futures of the mod on olive/orchard. end of the field turn options all before headland. If there are options after headland it will be very useful.

Regards,

**Comment by ZhooL** [comment]
Go to config menu and change headland distance to "x meters after end of field". Just cycle through the values...

**Comment by kurguplu** [comment]
Sorry for issue post. I put it to resolved but seems like you already
received it.

I find the setting, it was a stupid of me reading behind and beyond as same.

Keep up ty good work.

With kind regards,
Kaan
