### ISSUE TITLE
0,5 ° Richtungsänderung

### ISSUE THREAD

**Issue by Kynuska** [ZhooL/FS22_EnhancedVehicle#44]
Hallo. Würden Sie bitte in 0,5°-Richtung gehen? Um die Richtung der Texturen des Spiels anzupassen. (0 ° / 22,5 ° / 45 ° ...)
Ich entschuldige mich im Voraus, falls dieses Thema bereits geöffnet wurde.
Danke schön.
Kynuska
![fsScreen_2021_12_28_23_28_31](https://user-images.githubusercontent.com/15960970/147612520-36851ee4-1f12-4683-86f8-fe0fe4f96d02.png)

**Comment by ZhooL** [comment]
Tut mir leid, aber 0,5° Schritte werden nicht unterstützt und ich habe auch nicht vor sie zukünftig zu unterstützen. 1° ist das Minimum.
