### ISSUE TITLE
Gamepadeingaben / Spur versetzen / Lenkradius / Liniensichtbarkeit in Feldern

### ISSUE THREAD

**Issue by Kotlett** [ZhooL/FS22_EnhancedVehicle#45]
Hallo!

Erstmal: toller Mod mit sehr viel Potenzial. Habe alle anderen GPS-Mods dafür entfernt - allein, weil ich es praktisch finde, ein All-In-One Paket (GPS + zus. Anzeigen) zu haben.

Nun aber zu den Problemen / Anregungen:

1.) Bitte ändere die Eingabeerkennung für Gamepads so ab, dass man die Tasten zum durchschalten nicht wiederholt drücken muss, sondern sie auch halten kann. Was ich meine: wenn ich z.B. "Fahrspurbreite vergößern" auf _Stick-nach-links_ lege, so kann ich den Stick nicht einfach nach links halten, um die Breite immer weiter zu erhöhen. Stattdessen muss ich diese _Stick-nach-links_-Bewegung 600x wiederholen, bis ich endlich bei der von mir gewünschten Breite lande. Gilt für alle verstellbaren Werte (also auch verschieben etc.). Mit Buttons ist es das Gleiche: wiederholt drücken ist nötig, anstatt einfach gedrückt halten zu können.
Das Ganze ist recht Nerven- und Controllertötend. ;)

2.) Feature-Request: Vielleicht eine zusätzliche Funktion einbauen, wo er auf Befehl in die jeweils nebenliegende Spur wechselt - OHNE umzudrehen. Quasi wie beim überholen auf der Autobahn.

3.) Der Lenkradius beim wiedereinfädeln nach dem umdrehen ist recht zahm, so dass er verhältnismäßig spät erst wieder 100% in der Spur fährt. Das führt dazu, das zu Beginn des Feldes ggf. kleine Stellen nicht überfahren werden. Vielleicht lässt sich das einfädeln noch etwas flotter und präziser gestalten?

4.) Es wäre cool, die Navi-Linien etwas präsenter zu gestalten. Vielleicht etwas, wie einen "Gartenzaun", also eine Art Hochkant-Gitter (habe ich in einem anderen Mod mal gesehen). Die aktuellen Linien sind in hohen Feldern nur sehr schwer zu erkennen.

Ansonsten top Arbeit - weiter so! :)

Edit: einen Bug hab ich noch: wenn ich per Gamepad (Thumbstick) den Vorgewendemodus durchschalten will, zeigt er mir plötzlich hohe Zahlen (zb "-16666666", "-16666665" etc) statt der Bahnnummern an. Genauso beim drehen der Bahnen etc.

**Comment by ZhooL** [comment]
Danke für das Feedback.

zu 1. Das hatte ich schon drin, war dann allerdings viel zu schnell -> man konnte nicht mehr fein genug justieren. Aber ich schau mir das nochmal an... irgendeine Art von Verzögerung reinbasteln oder sowas

zu 2. Hmm sowas war nie geplant und ich möchte eigentlich nicht noch mehr Tasten(kombinationen) belegen. Der Anwendungsfall erschließt sich mir auch noch nicht so ganz :D 

zu 3. Nein. Die Funktion fasse ich nicht mehr an - bin froh, dass es so tut wie es gerade tut. Sorry. Mehr Vorgewende fahren, dann ist mehr Platz zum "langsamen" wenden

zu 4. Auch eher Nein. Die Linien der Spuren (die gelblichen) bleiben so - die sollen nicht zu präsent sein. Die roten Linien mit den Spikes für die Arbeitsbreit ist m.E. schon auffällig genug (vielen sogar zu auffällig). Du kannst die Höhe der Stacheln in der config XML manuell erhöhen.

zum Bug: Kannst du das etwas mehr beschreiben? Was war die Ausgangssituation? War der Spurassistent an/aus?

**Comment by Kotlett** [comment]
Ich beziehe mich mit meinen Vergleichen auf diesen GPS Mod: https://cornhub.army/ls22-vca-gps-mod/
Der ist recht komfortabel zu bedienen und optisch ebenfalls gut zu erkennen. 

Zu 1: ja, vielleicht einfach mit einer halben Sekunde Verzögerung oder so anpassen. Im Moment drückt man sich echt den Wolf. ;)

Zu 2: Gibt durchaus Szenarien - auch hier sieht man gut im oben erwähnten Mod, wie das umzusetzen ist.

Mir erschließt sich auch nicht ganz, weshalb ich Spuren, einklinken und "Folgelinie (rot)" separat an- und abschalten muss. Lässt sich dass nicht einfach auf eine Taste legen (Also einfach GPS an (alle Linien) und GPS aus ?).  Ggf. mal den oben erwähnten Mod anschauen (mit Spur anzeigen auf (immer/hoch), dann weißt Du was ich meine. Im Moment muss man gefühlt sehr viel separat an- und abschalten bei Deinem Mod, beim anderen geht das alles über eine Funktion.

Gibt es Spikes auch für die gelben, oder nur für die roten Linien? Dann wäre das in der Tat eine Alternative zum "Gartenzaun".

Zum Bug: Spurassi war an, denn ohne lassen sich die Spuren ja nicht ändern. Ich glaube das ist immer dann, wenn man Standardspuren ohne feste Arbeitsbreite nutzt und dann versucht diese zu verändern (also zb um 1° drehen). Also zb. Traktor mit normalem Kipper-Anhänger.


Ganz wichtig: alles nur gut gemeinte Kritik, KEIN meckern!! Ist sowieso schon echt toll, was Du gebaut hast und viel mehr, als ich überhaupt könnte! ;)

**Comment by ZhooL** [comment]
Ich möchte und werde EV nicht mit VCA vergleichen. Das Thema ist damit abgeschlossen.

zu 1: wird in 1.0.1.0 implementiert sein

zu 2: wird in 1.0.1.0 implementiert sein

zum Bug: wird in 1.0.1.0 gefixt sein

Spikes auf gelbe: wird in 1.0.1.0 implementiert sein

Die Liniengeschichte ist historisch gewachsen. Hat ja alles angefangen mit das man nur die Fahrtrichtung fixieren kann und es gar keine Fahrspuren o.ä. gab. Daher die Rshift+Pos1 um die Funktionalität mit Linien zu unterstützen. Der Fahrspurassistent kam später dazu und kann separat mit RCtrl+Numpad1/2 an/aus/berechnet werden. Es gibt Leute, die wollen gar keine Linien und können sie ausschalten und "blind" die Spurhaltung nutzen etc. Dann gibt's welche die haben immer alle Linien etc. an (ich z.B.) und es gibt welche die nutzen sowohl mal Fuhrhaltung und mal nur snap to direction (auch ich) und die können die Spurlinien separat ausschalten.
