### ISSUE TITLE
Gamepadeingabe blendet HUD aus und blockiert teilw. (Menü)Steuerung

### ISSUE THREAD

**Issue by Kotlett** [ZhooL/FS22_EnhancedVehicle#47]
Einen Bug soeben noch gefunden:

Wenn ich per Gamepad Tastenkombi (Logitech F710 = XBOX 360 / LB + RB + RS-Y (+-) = also Tastenkombi und rechter Thumbstick hoch oder runter ) die "Vorgewendedistanz ändern" will, blendet er plötzlich das gesamte HUD bis auf die Wettervorhersage und Minikarte aus und blockiert teilweise sogar die Steuerung im Menü. ZB scrollt dann das Mausrad im Menü nur noch in eine Richtung. 

Über die gleiche Kombination nur Stick rechts/links geht übrigens zB das drehen der Linien einwandfrei (und der Bug mit den 1.6666665er Zahlen beim drehen mit Standardspuren ist übrigens weg ;)).
Bin mir nicht ganz sicher, ob es an dieser speziellen Tastenkombi (rechter Thumbstick hoch/runter) oder der Vorgewendeeinstellung himself liegt.

Normales Fahren ist noch möglich, ebenso wie das wechseln zu einem anderen Fahrzeug, wo dann alle Anzeigen wieder da sind. Die Anzeigen am ursprünglich betroffenen Fahrzeug bleiben aber auch nach zurückwechseln defekt. Erst nach erneutem Laden des Spielstands zu beheben.

Fehler taucht ohne den Mod nicht auf. Spurassi und einraste an/aus macht keinen Unterschied.

Bin mir nicht ganz sicher, ob es an dieser speziellen Tastenkombi oder etwas anderem liegt. Generell scheint der Mod Probleme mit Analogen Eingaben (Thumbsticks) zu haben - die sind aber aufgrund der vielen Optionen und begrenzten Anzahl von Controllereingaben selbstverständlich unverzichtbar.

**Comment by ZhooL** [comment]
Schau mal bitte in die log.txt.... das klingt nach einem Script-Fehler, der eigentlich was ins Log schreiben sollte

**Comment by ZhooL** [comment]
Habe den Fehler gefunden - wird in der nächsten Version gefixt sein.

**Comment by Kotlett** [comment]
Ah okay, wollte gerade die Log hochladen - top, danke! :)
