### ISSUE TITLE
Bekomme die Mod nicht installiert

### ISSUE THREAD

**Issue by Roomzie** [ZhooL/FS22_EnhancedVehicle#5]
Hallo!

zunächst mal danke danke danke!!! 

Ich versteh immernoch nicht warum man in einem Landwirtschaftssimulator kein GPS standardmäßig im Spiel hat, daher vielen dank dass du dich darum gekümmert hast. Jedoch hab ich ein problem beim Installieren, ich speichere die ZIP datei direkt in den "MyGames/LS22/Mod" Ordner, die Mod erscheint aber nicht im Aktivierungs-Screen ingame. 

Mache ich etwas Falsch oder könnte das ein Bug sein? 

Danke im Voraus!

**Comment by scud1984** [comment]
Das Archiv, das du hier runter lädsts, musst du entpacken. Darin befindet sich dann ein Ordner den du neu als *.ZIP packen musst.

**Comment by Roomzie** [comment]
Habe es endlich geschafft, war leider nicht wie du gesagt hast aber danke trotzdem für die Hilfe, für leute die auch den Fehler hatten, mann muss nur die Zip aufmachen und in der Zip Datei ist noch eine Zip Datei die man sich in den Ordner Zieht, Heisst "FS22_EnhancedVehicle.zip"

**Comment by ZhooL** [comment]
Äh ja, das ist auch ein Thema "wie" man es von Github runter lädt. Von denjenigen, die diesen Mod jetzt schon während der Entwicklung ausprobieren möchten, erwarte ich ein gewisses Grundverständnis von Github. Die finale Version werde ich dann auch wohl wieder über modhoster.de anbieten.
