### ISSUE TITLE
Steering Performance Improvement suggestion

### ISSUE THREAD

**Issue by crouser7** [ZhooL/FS22_EnhancedVehicle#50]
Hey Zhool,

first of all big big thank you for this already awesome and great mod.

I have a suggestion to improve the Line Aquisition when turning around:

When turning around automatically you start steering towards the new line quite early and with a moderate steering angle.
Delaying this and steering tighter would help to get on the new line a lot quicker.

Common practise for actual GPS Steering Systems in Agriculture is to actually even drive one Overshoot (go past the desired line, then get directly back on. Not by much just about 1m or less)
This helps especially for trailed implements like seeder or cultivator to be on the line quicker then without.

Having the implement quicker on line reduces the need for headland that needs to be reworked at the end.

If you have question in this area let me know, i do work in this particullar area. 
Thank you a lot for your work
Crouser7

**Comment by ZhooL** [comment]
I'm aware that my method of turning is not optimal. It's simple and "it works" somehow. I made some smaller adjustments, but what is working good for front-axle steering vehicles ends up messy with back-axle steering vehicles like combines. So my parameters are some sort of compromise between them.
