### ISSUE TITLE
Headland calculation not consistend and often not correct

### ISSUE THREAD

**Issue by crouser7** [ZhooL/FS22_EnhancedVehicle#51]
Hey Zhool,

i have seen several occasions where the distance to the field end (the headland point for automatic turn around) is calculated incosistent on the same field. On on Side of the field it did overshoot the field boundary by quite a bit even though the turn around point was 1 working width before that.

In other occasions the vehicle did turn around for example with the 36m sprayer and it was set to one working width from the end, but it turned around about 10m early.

Yours Crouser7

**Comment by ZhooL** [comment]
Better name for your issue: "Game engine is not reporting consistend ground values at pos x, y" :D 

I'm aware of that behaviour on some fields and I still believe these are issues with the fields boundries on the map, but I'm going to debug that one final time.

**Comment by ZhooL** [comment]
Should now work as expected :)
