### ISSUE TITLE
Brake Force Options?

### ISSUE THREAD

**Issue by Jayshua83** [ZhooL/FS22_EnhancedVehicle#52]
I've noticed that this mod modifies the Brake Force by A LOT. I like it but other users on my server won't if I start to run this over "other" lesser mods. Is there anyway to have an option for how much Brake Force is applied? Like when you release the Gas Pedal and how fast you slow down.

**Comment by ZhooL** [comment]
Please check for other mods you might have installed because this mod does not modify brake force at all. The only place this mod interacts in "forward-backwards" movement is the parking brake and a parking brake is used when parking a vehicle and not for regular braking.
