### ISSUE TITLE
Verstänliche Anleitung

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#53]
Halle es wäre schon wenn man eine verstänliche anleitung hätte denn bei mir fährt er total komisch und das mit denn vorgewende um drehn geht irgiwe auch nicht   jedenfals weiß ich nicht wie ich denn mod richtg steure was das GPS an geht

**Comment by Alex30RU** [comment]
Kann die Verschmutzung angezeigt werden?

**Comment by ZhooL** [comment]
Nein, die Verschmutzung wird nicht angezeigt.

**Comment by Alex30RU** [comment]
Kann ich eine Show machen? Statt zu malen.

**Comment by ZhooL** [comment]
Zoddel hat ein nettes Video zum EV gemacht: https://agraz-mods.de/enhanced-vehicle-fs22/
