### ISSUE TITLE
Tempomat

### ISSUE THREAD

**Issue by Stefan883** [ZhooL/FS22_EnhancedVehicle#54]
Hallo zusammen.

Ich hab da ein kleines Problem. Bei mir geht plötzlich der Tempomat währen der Feldarbeit nicht mehr. Dabei wird mit dem GPS System von Enhanced Vehicle das Feld abgefahren. Nach beenden des Spiels und kurzer Wartezeit läuft alles eine Zeit lang ohne Problem. Mal kommt der Fehler nach 1 min. oder erst nach 2 Std. Allso total unterschiedlich wann es auftritt.

Ist da was bekannt ?

Anbei mein log Datei.

Dank schon mal im voraus.

Stefan
[log.txt](https://github.com/ZhooL/FS22_EnhancedVehicle/files/7798894/log.txt)

**Comment by ZhooL** [comment]
Vielleicht passiert es jetzt nicht mehr. Hoffentlich :)
