### ISSUE TITLE
Frage zu Symbol

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#55]
was heißt das? ^^
![grafik](https://user-images.githubusercontent.com/26688591/147877089-de359a09-1588-4427-b399-4f179024670f.png)

**Comment by ZhooL** [comment]
Keine Ahnung - denn das ist nicht von meinem Mod.

**Comment by DarthBaobab** [comment]
@Blackjack155 Das kommt von VehicleInspektor vom HappyLooser. Dachte auch erst das es vom EnhancedVehicle kommt ist aber nicht so. Wofür es gut ist, habe ich bisher auch nicht herausgefunden.

Edit: Drück mal F12 dann hast du eine Maus und dann kannst du auf das Symbol klicken. Scheinen die Modeinstellungen dann zu sein.
