### ISSUE TITLE
MP Bug 

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#56]
Ich kann nicht mit dem Tacktor fahren handbreme ist deaktieviert 
er nimmt kein gas an garnichts

**Comment by ZhooL** [comment]
Bist du sicher, dass du a) überhaupt erstmal mit "RStrg+Numpad Enter" die Funktionalität Handbremse angemacht hast und danach b) mit "Numpad Enter" die Handbremse gelöst hast? Wenn das "P" Symbol im HUD leicht transparent ist, ist die Funktionalität aus. Ist das "P" Symbol klar rot ist die Bremse gezogen.

**Comment by Blackjack155** [comment]
P symbol ist nicht vorhanden und in der Config ausgeschalten

**Comment by ZhooL** [comment]
Dann stell in der Konfig unter "Globale Einstellungen" die "Handbremse" wieder an, schau das das Symbol dann auf grün ist und danach kannst du es global wieder ausschalten. Vermutlich hast du es global ausgeschaltet als die Bremse gezogen war.

**Comment by Blackjack155** [comment]
oder ein conflig mit VCA ?

**Comment by ZhooL** [comment]
Keine Ahnung. Ich nutze kein VCA und ich teste mein Mod nicht gegenüber VCA auf Kompatibilität. Am besten entscheidest du dich für eins von beiden.

**Comment by Blackjack155** [comment]
naja dein GPS kann ich leider nicht nutzen weil ich damit nich klar komme da es nicht so fährt wie du das erstelt hast ^^
