### ISSUE TITLE
Frage 

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#57]
das einzige was ich jetzt nicht versteh is das umdrehn am feld ende macht er das automaitsch und wie stelle ich das ein das er weis wann das feld zu ende ist? is bis jetzt das einzige was ich nicht heraus gefunden habe

**Comment by ZhooL** [comment]
Ebenfalls im Konfigurationsmenü im Abschnitt "Vorgewende". Dort kannst du einstellen, was er machen soll und wieviel Meter vor/nach dem Feldende.

**Comment by Blackjack155** [comment]
@ZhooL ja aber wie stell ich is es ein das er weiß wann das ende des feldes ereicht ist??

**Comment by ZhooL** [comment]
Gleiche Antwort wie oben... du stellst es im Menü ein und der Rest passiert dann automatisch.

**Comment by Blackjack155** [comment]
hab hinbekommen danke sehr :)
