### ISSUE TITLE
Error in game 

### ISSUE THREAD

**Issue by criss20ster** [ZhooL/FS22_EnhancedVehicle#58]
I have this mistake error in the see picture 

https://drive.google.com/file/d/1IMXnjPdtxImeu0S2aJr58azS5sxftniT/view?usp=sharing

**Comment by ZhooL** [comment]
I'm sorry, but that is not an error in my mod but a missing translation in your language of the vehicle you're using. Try to find the author of the vehicle and ask him/her to include translations.
