### ISSUE TITLE
Mod does not load with steam version of FS22 ver. 1.1.1.0 (26336/54525)

### ISSUE THREAD

**Issue by Dosahka** [ZhooL/FS22_EnhancedVehicle#6]
Just downloaded the mod a few hours ago and reinstalled FS22 two times, but the mod still not loading and not recognised by the game.

**Comment by Dosahka** [comment]
when i downloaded the file it was double zipped the mod within the mod

**Comment by ZhooL** [comment]
Ensure to just put the FS22_EnhancedVehicle.zip in the mods folder and not a zip containing a zip. It depends how exactly you download content from Github.
