### ISSUE TITLE
VCA

### ISSUE THREAD

**Issue by NiklasWGC** [ZhooL/FS22_EnhancedVehicle#61]
Is the mod compatible with the vehicle control addon?

**Comment by ZhooL** [comment]
I don't know and to be honest I don't care. I guess not, cause both mods are basically providing same/similar features. I heard from some people that they can co-exist enabling a feature in EV and disabling it in VCA or vice versa.

**Comment by NiklasWGC** [comment]
ok thank you for the quick answer and the cool mod
