### ISSUE TITLE
Parkbremse

### ISSUE THREAD

**Issue by Bandesss** [ZhooL/FS22_EnhancedVehicle#63]
Hallo Zhool gutes neues dir ;)
Also meine Parkbremse geht nicht, egal welche Taste ich belege bleibt sie immer Grün im MP
Gruß Bandes

**Comment by Blackjack155** [comment]
STRG+Nummpad Enter Probiert?

**Comment by Bandesss** [comment]
Ich habe die Taste selber eingestellt 
Habe ich versucht geht auch nicht im Mp

**Comment by ZhooL** [comment]
Die Parkbremse funktioniert wie sie soll in SP als auch MP. Prüfe Tastatur- und Andere-Mods-Konflikte. RStrg+Numpad Enter schaltet das Ding an, Numpad Enter aktiviert/löst die Bremse (wenn die Funktionalität angeschaltet ist)

**Comment by Bandesss** [comment]
Ja vielen Dank diese Funktion mit an und abschalten, habe ich leider übersehen
Danke Euch
Thema erledigt

**Comment by Kynuska** [comment]
Bitte versuchen Sie, dass jemand die Feststellbremse mit manuellem Getriebemodus mit Kupplung betätigt. Entweder ich bin dumm oder ich weiß es nicht.
