### ISSUE TITLE
eine bitte Vorgewende

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#64]
wäre es möglich leichter ein vorgewende zu fahren?  in dem er das feld erkennt und das berechnen kann? in real kannst du ein feld abfahren im GPS und dann auch das vorgewende damit fahren  wäre das möglich oder hast du das nicht vor gesehn?

**Comment by ZhooL** [comment]
Nein, das geht nicht und ich habe es auch nicht vorgesehen.
