### ISSUE TITLE
Keys in help menu

### ISSUE THREAD

**Issue by JayJay1968** [ZhooL/FS22_EnhancedVehicle#66]
It's not possible turn of keys in help menu. Setting showKeysInHelpMenu="false" in modSettings still shows the keys.

**Comment by ZhooL** [comment]
Yes I noticed it already but wasn't able to fix is yet. It's on my ToDo list

**Comment by ZhooL** [comment]
Should be resolved in next release. I had to change the default binding for moving the offset line to something else.
