### ISSUE TITLE
Lines?

### ISSUE THREAD

**Issue by Jayshua83** [ZhooL/FS22_EnhancedVehicle#67]
![GPS_lines](https://user-images.githubusercontent.com/11082446/148485567-9641e0ea-0cd8-4231-8ce4-a75bc146439a.png)

Not sure why but sometimes I get Orange Vehicle Lines and Smaller Red ones. Normally the Vehicle lines are always Red and there is only 1 set NOT 2. What is going on in this photo?

**Comment by ZhooL** [comment]
Hi, there're always the spikey orange/light red lines and the dark red smaler lines. First one display the working width of the current attachment from the view of the vehicle. The short ones are showing the attachments current orientation. In case of a cutter both are pointing in the same direction and kind of overlap. But attach a pulled sprayer for example and you will see the difference.
