### ISSUE TITLE
Enhanced Tempomat :) 

### ISSUE THREAD

**Issue by 0scarZulu** [ZhooL/FS22_EnhancedVehicle#68]
Moin :) 

ist abzusehen das EV die Funktion bekommt, das der Tempomat mehrere Stufen hat? So wie es beim VCA umgesetzt ist? Taste 1-3 Tempostufen. Finde das würde den Mod noch komplettieren und eine verwendung des VCA obsolet machen. Was ohne hin sinn macht, da sich die Spurführung beißt ...

**Comment by ZhooL** [comment]
Sorry, das Feature ist nicht geplant. Du kannst ja die jeweiligen Funktionen in den Mods ausschalten, wo du sie nicht brauchst (zB Spurführung)

**Comment by 0scarZulu** [comment]
Spurführung lässt sich im VCA leider nicht deaktivieren. Und ich nutze nun mal die von EV lieber

**Comment by ZhooL** [comment]
Ich kann es nicht prüfen - habe kein VCA. Habe jedoch Streamer gesehen, die beides drauf haben und es bei VCA deaktiviert hatten.
