### ISSUE TITLE
[Anregung] Visuelle Linien verbessern

### ISSUE THREAD

**Issue by Gariot** [ZhooL/FS22_EnhancedVehicle#7]
Moin,

danke fuer die extrem nuetzliche Mod und vor allem fuer den Spurassist. Nutze ich bereits fleissig im Stream :D 

Habe gerade die neue Version getestet und wuerde vorschlagen die Linien evt. vor allem bei Dreschern optisch etwas anzuheben da man sie in der Frucht sehr schlecht sehen kann. 

Moeglicherweise waeren dickere Linien sogar schon ausreichend genug. 
Vielleicht findest du auch farben die einen besseren kontrast bieten.
Die Farbe der Linien koennte man auch anpassen. Je nachdem ob der Assistent an ist eine andere Farbe z.b. wie schon bei der Anzeige ueber dem Drehzahlmesser. Rot an/Gruen aus und so eben die Farben der aeusseren Linien.

Hauptsache aber man kann sie besser sehen :D

**Comment by Tensuko** [comment]
#1 Linienhöhe wäre vlt noch ein Punkt ja. Einstellbar ob hoch oder niedrig.

**Comment by nixmomo** [comment]
Wie hast du denn die Linien enabled? Bei mir funktionieren die nicht, egal auf welche Taste ich es lege

**Comment by ZhooL** [comment]
In den aktuellen 0.9.9.x Versionen gibt es eine weitere visuelle Hilfe - die senkrechten Linien. Die Höhe davon kann in der XML (spikeHeight="0.750000") konfiguriert werden. Die Höhe über dem Boden kann mit distanceAboveGroundVehicleSideLine="0.250000" angepasst werden.
