### ISSUE TITLE
allow more decimal places in the angle settings

### ISSUE THREAD

**Issue by andreasthu** [ZhooL/FS22_EnhancedVehicle#70]
Hello Zhool
is it possible to allow more decimalplaces in the "Snap To Angle" field?
i have a map with 2 additional terrainangle settings.
![fsScreen_2022_01_09_04_37_31](https://user-images.githubusercontent.com/24860501/148668480-92730cff-f414-4e30-a1ad-d760ba925e9d.png)

so my helper (and the terrain) can set  all 5,625 degrees (22,5° /2 = 11,25° /2 = 5,625°)
it was a great help when i will create new fields with the plow.

lg
andreas

**Comment by Kynuska** [comment]
https://github.com/ZhooL/FS22_EnhancedVehicle/issues/44#issue-1090164206

**Comment by andreasthu** [comment]
Oh, ok.
Know you on wich place i must edit the lua, so i have more decimals ?
Lg
Andreas

**Comment by ZhooL** [comment]
As said before: 1° is the smallest unit. I wouldn't recommend to try to adjust the source... there're too many places where the angle is rounded.
