### ISSUE TITLE
 Gesamt gewicht 

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#74]
kann es sein das dein mod nicht mehr als 44,4 tonnen anzeigen kann?

wär schön wenn das höher gehn würde das man weiß was man maximal wiegt und nicht einfach aufhört

**Comment by ZhooL** [comment]
Das kann ich nicht beurteilen - ich zeige das an, was die Engine mir gibt.

**Comment by vitalii2011** [comment]
Is it possible to take into account the weight of loaded pallets?
