### ISSUE TITLE
Anzeigen auf Dedi-Server

### ISSUE THREAD

**Issue by FreelancerTrent** [ZhooL/FS22_EnhancedVehicle#75]
Hi Zhool,

mit der Version 1.1.3.0 wird auf dem Dedi-Server die Motortemperatur und der Momentanverbrauch nicht mehr angezeigt.

Es ist unabhängig davon, ob man als normaler Spieler oder als Admin angemeldet ist. Auch ein zurücksetzten der Config und ein neu laden der .xml brachten keine Besserung.

mfg Trent

**Comment by Blackjack155** [comment]
das ist normal und kein fehler es geht leider nicht anders

**Comment by ZhooL** [comment]
Korrekt - steht auch in der Doku, dass diese Werte im Multiplayer nicht zur Verfügung stehen.
