### ISSUE TITLE
Parking “P” don’t work when GPS mod is active

### ISSUE THREAD

**Issue by Inoque71** [ZhooL/FS22_EnhancedVehicle#76]
The park function doesn’t work when the GPS mod from Wosper is active (Alt+x). If the guidance steering isn’t active the park key work.

**Comment by ZhooL** [comment]
Sorry, but can't fix that. Both mods are hooking ito the physics of the vehicle and it seems the GPS is doing that after my mod did its changes. Last one wins.

**Comment by Inoque71** [comment]
You don’t need apology. Only report issue but if the same mod used the same physics we can’t do anything is a limitation of the game.
Thanks for your feedback.
Regards
