### ISSUE TITLE
Xbox Series Controller Mappings not working all the time

### ISSUE THREAD

**Issue by DrFeelgood66** [ZhooL/FS22_EnhancedVehicle#79]
Hello

I have set reverse snap/track direction (180°) (= turnover) to Right Bumper + D-pab UP and it works, but if i jump out of my Tractor og jump back in my Tractor, and try to use it, it does not work. Then i go to the button mappings for the controller, and the mapping i made earlier is still there but does not work. I have to reassign it to the same mapping again, and save, and now it works. I have to do this every time.

This is what the inputbinding.xml look like for that action

    <actionBinding action="FS22_EnhancedVehicle_SNAP_REVERSE">
        <binding device="KB_MOUSE_DEFAULT" input="KEY_rctrl KEY_home" axisComponent="+" neutralInput="0" index="1"/>
        <binding device="0_XINPUT_GAMEPAD" input="BUTTON_6 BUTTON_17" axisComponent="+" neutralInput="0" index="1"/>
    </actionBinding>

**Comment by ZhooL** [comment]
Hi @DrFeelgood66 

I can reproduce that, but it seems to be a matter of duplicate bindings. RB+DP-Up is already occupied by "turn on/off rotating beacon". If I delete that binding the reverse direction binding is working always fine for me.

Please verify.

**Comment by DrFeelgood66** [comment]
Okay thanks i will try that :)
