### ISSUE TITLE
[Anregung] Erweiterung um Tempomatstufen

### ISSUE THREAD

**Issue by rondo24xx** [ZhooL/FS22_EnhancedVehicle#8]
Die Erweiterung um weitere Tempomatstufen würde sicherlich gut in die MOD passen und passt sicherlich gut in das Thema der MOD "EnhancedVehicle".

Aber bitte nur als Anregung verstehen... keinen Stress...

VG Rondo

**Comment by ZhooL** [comment]
Hi, so ein Feature ist nicht geplant. Außerdem hat das Spiel bereits so eine Art weitere Tempomatstufe eingebaut, wenn du die Tempomat-aktivieren Taste festhälst.
