### ISSUE TITLE
About Chinese Translation

### ISSUE THREAD

**Issue by aini1123** [ZhooL/FS22_EnhancedVehicle#80]
Hi. I have completed the Chinese translation of the latest version 1.1.3.1, but due to the relationship between the Chinese font library of the game, the translation may not be fully displayed in the game, but it does not hinder normal use. How do I upload it ne
[translation_cs.zip](https://github.com/ZhooL/FS22_EnhancedVehicle/files/7921956/translation_cs.zip)
x

**Comment by ZhooL** [comment]
Thank you :-)

Translation will be included in the next release. Afterwards you should be able to create pull requests here in Github to provide changes.
