### ISSUE TITLE
Anzeige Entfernung bis zum Vorgewende

### ISSUE THREAD

**Issue by 0scarZulu** [ZhooL/FS22_EnhancedVehicle#81]
Hallo :)

ich nutzt deine Spurführung sehr gern und auch das damit verbundene Vorgewende Management. Jetzt wäre meine Frage ob es möglich wäre noch eine Anzeige für die Entfernung einzubauen. zB oberhalb der Gradzahl, das Feld ist noch frei. 

Vorstellen würde ich mir ungefähr das ab einer Entfernung von X- 20m die Zahl erschein und dann bei nur noch 10% restweg sich rot färbt das man quasi gleich ausheben soll. Für mich wäre dies eine super ergänzung um den Punkt für das ausheben noch besser abstimmen zu können. 

Beste Grüße 
0scarZulu 
[Agro Pics Ost](https://www.instagram.com/agro_pics_ost/)

**Comment by ZhooL** [comment]
Hmm, das Problem an der Sache ist, dass ich "permanent" das Feldende suchen muß um die Restdistanz berechnen zu können. Das kostet Rechenzeit. Als Workaround berechne ich nun nur einmal die Sekunde den Abstand und lasse diesen im HUD anzeigen.
Mal beobachten, wie das so läuft. Wird in 1.2.0.0 drin sein.

**Comment by 0scarZulu** [comment]
Cool danke für die schnelle Umsetzung :) Ich dachte die Berechnung muss ja eh geschehen. Oder was vlei auch gut wäre, wenn es zuviel Rechenleistung nutzt. Das er bei nem zB 2m bevor das Eingestellte Ende erreicht ist nen signal gibt oder so .. so das man weiß ok gleich gehts los ..
