### ISSUE TITLE
Motor Auslastung

### ISSUE THREAD

**Issue by Blackjack155** [ZhooL/FS22_EnhancedVehicle#83]
Guten morgen 
wäre es denn noch möglich zu seh wie weit die motorauslastung beträgt? wäre sicher eine nette kleine anzeige :)

**Comment by ZhooL** [comment]
Nein. Dafür gibt es Mod im Modhub. Bitte verwende das.

**Comment by Blackjack155** [comment]
wolte beben nicht so viele mods verwenden damti die kompatibilitär gewärd ist? !
