### ISSUE TITLE
Keine Einstellungen sichtbar

### ISSUE THREAD

**Issue by Kotlett** [ZhooL/FS22_EnhancedVehicle#88]
Servus!

Seit der letzten Version (?) sind die Einstellungen nicht mehr zugänglich und die log wirft einen LUA Error (siehe Bilder).
![DSC_0106](https://user-images.githubusercontent.com/96910665/153572408-b3c49757-ef6b-4b74-9be5-55c3bbe9aa6a.JPG)
![DSC_0107](https://user-images.githubusercontent.com/96910665/153572412-b44759fa-2556-41c6-92a5-790ffca3f4b7.JPG)

Außerdem hatte ich letztens wieder diesen "23.54473954875035790°" Anzeige-Fehler, kann diesen aber gerade nicht reproduzieren.

Ansonsten wie immer: TOP Arbeit. Bei jedem großen Feld bin ich so froh, den EV zu haben! :)

**Comment by ZhooL** [comment]
Bitte nutze den korrekten Link zum runterladen https://github.com/ZhooL/FS22_EnhancedVehicle/releases/latest/download/FS22_EnhancedVehicle.zip und der Mod hat "FS22_EnhancedVehicle.zip" zu heißen und nicht FS22_SCR_EnhancedVehicle.zip.

**Comment by Kotlett** [comment]
Den Mod habe ich von hier herunter geladen, ist also Dein Original - nur von mir umbenannt für meine Serverhierarchie. 
Du hast allerdings Recht - diese Umbenennung scheint er, im Gegensatz zu anderen Mods, nicht zu vertragen. Ich werde das dementsprechend anpassen. :)

Vielen Dank für den entscheidenden Hinweis. Hätte ich mir eigentlich auch zusammenreimen können, aber da stand ich wohl auf dem Schlauch. ;)

PS: Wo in den XML/LUAs ist denn festgesetzt, wie die ZIP heißen muss?
