### ISSUE TITLE
Variable snap degree

### ISSUE THREAD

**Issue by Elmegaard** [ZhooL/FS22_EnhancedVehicle#9]
Would it be possible to add a setting for changing the amount of degrees to snap to? Currently it snaps to the nearest whole degree, which means you have to be pretty spot on before enabling the snapping. If I could change that to the nearest 5 degrees in the config it would make it much smoother for setting the initial snap point.

Example: 92.1 degrees would snap to 90 degrees instead of 92 degrees and 92.8 would snap to 95, if this setting was set to 5 instead of 1.

Thanks for a great mod.

**Comment by ZhooL** [comment]
Implemented in 0.9.7.0
