### ISSUE TITLE
Add feature to turn off and hide all track snapping UI

### ISSUE THREAD

**Issue by sjmills** [ZhooL/FS22_EnhancedVehicle#94]
I find the large number of keys needed to use the track snapping to be too confusing, and I’m not going to use it. So, it would be great if there was a way to hide the 6-segment UI above the speedo/tach, since it’s just in the way. That stuff really should be a separate mod. The driveline controls and fuel usage are the real meat & potatoes of this mod.

**Comment by ZhooL** [comment]
Hi, go to the options menu (RCtrl+Numpad /) and turn the parts of the UI, you don't want to see, off. It's all in the menu.
