### ISSUE TITLE
Dedicated Server MP

### ISSUE THREAD

**Issue by FarmerJon1066** [ZhooL/FS22_EnhancedVehicle#97]
When running the game on a dedicated server with the EnhancedVehicle mod, after a reboot of the server or being ideal for a long period of time the vehicles will no longer be able to go forwards or backwards. The wheels can still be turned on the they can turn on and off. The diff will unlock and drive mode. I added the server log file. If I deactivate the mod after the issue happens, the tractors are drivable again. If I load the game in single player once the issue happens it will persists until the mod is removed. 

[log.txt](https://github.com/ZhooL/FS22_EnhancedVehicle/files/8469250/log.txt)

**Comment by ZhooL** [comment]
Sorry, I can't look deeper into this issue. You have a lot of mods active a lot of errors/warnings from other mods. Also your EV version is outdated - please update to latest 1.2.2.0. It could also be a mod compatibility issue with other mods modifying drive behavior (e.g. REA). Also check the status of the parking brake or try to toggle it and see if vehicle moves again.
