### ISSUE TITLE
seit Patch 1.4.1.0 funktionieren die difflock und parkingbrake nicht mehr bei allen Fahrzeugen

### ISSUE THREAD

**Issue by 112TEC-Chris** [ZhooL/FS22_EnhancedVehicle#98]
Hallo,
ein paar meiner Fahrzeug lassen sich nicht mehr "entparken" undf die Differentialsperren funktionieren bei den gleichen Fahrzeugen auch nicht. Das sind alles Mods. Gibt es da irgendetwas zu beachten oder ist das ein Bug?

**Comment by ZhooL** [comment]
Hi, ohne deine log.txt kann ich da keine weiteren Aussagen zu treffen. Ich vermute stark einen Konflikt mit anderen Mods, die ebenfalls auf das Fahrverhalten einwirken (VCA, REA, ...)

**Comment by 112TEC-Chris** [comment]
Na dann hab ich ein Problem. Denn in der Log gibt es keinen Fehler und auch kein Warning. Die Mods reagieren einfach nicht auf die Tasten. Und VCA, REA, etc. nutze ich nicht.

**Comment by jason0611** [comment]
Es scheint so, dass durch den Patch bei vielen Spielern die Tastenbelegungen verloren gegangen sind. Schau mal nach, ob Du vielleicht die Tasten neu zuweisen musst.

**Comment by 112TEC-Chris** [comment]
Nein die Tastenbelegung ist nicht weg. Denn bei den meisten Fahrzeugen funktioniert ja noch alles. Nur ein paar Fahrzeuge reagieren seit dem Patch nicht mehr auf die Tasten. Stand aber schon in meinem ersten Post drin ;)

**Comment by jason0611** [comment]
Dann poste bitte das Logfile. Ohne  ist alles weitere Spekulation.

**Comment by 112TEC-Chris** [comment]
Ich weiss zwar nicht was du damit willst, weil, wie ja bereits geschrieben, da steht nix drin.

[log.txt](https://github.com/ZhooL/FS22_EnhancedVehicle/files/8549928/log.txt)

**Comment by 112TEC-Chris** [comment]
Hi, 
Ich hab etwas entscheidendes ausfindig gemacht. Alle Mods in meinem Modordner mit vehicletype "car" haben das Problem. 

Vehicletype Car entspricht ja basedrivable plus der Spezis tensionbelts und foldable. 

Setze ich als in den Mod basedrivable + der Spezis, ist das Ergebnis das gleiche. 
Nehme ich aber da tensionbelts raus, funzt beides. Differentialsperren und Handbremse. 

Was die Sache noch komischer macht ist, dass die Fahrzeuge aus dem Spiel mit vehicletype "Car" keine Probs haben.

**Comment by ZhooL** [comment]
Ein VehicleType "car" ist mir nicht bekannt und kann eigentlich nicht aus dem Basisspiel kommen. Die LUA Sourcen kennen kein "car".  Hast du mir mal ein Mod, bei dem das bei dir nicht funktioniert?

**Comment by 112TEC-Chris** [comment]
Ich schrieb von vehicletype. Das ist nicht das gleiche wie Specialization.

```
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicle type="car" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../shared/xml/schema/vehicle.xsd">**
```

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=235262&title=fs2022
und als Beispiel aus dem Spiel der Lizard Pickup1986

**Comment by ZhooL** [comment]
Ich kann es nicht nachstellen. Ich hab den Lizard 1986 genommen und die FS22_UniversalAutoload Mod. Egal ob ich was geladen habe oder Spanngurte angelegt/nicht angelegt... Die EV Festellbremse und/oder Diffs funktionieren wie gewollt.

Bitte mach einmal den Test und entferne die UniversalAutoload Mod und schau ob es dann funktioniert.

**Comment by 112TEC-Chris** [comment]
ich schrieb doch die Fahrzeuge aus dem Spiel funktionieren nur Mods funktionieren nicht
"Was die Sache noch komischer macht ist, dass die Fahrzeuge aus dem Spiel mit vehicletype "Car" keine Probs haben." ;)

Bitte lies genau was ich schreibe.

**Comment by 112TEC-Chris** [comment]
Lizard Pickup aus dem Spiel **_OK_**
Lizard Cross Mod **_nicht OK_**

**Comment by ZhooL** [comment]
Auch mit dem Cross bekomme ich es nicht nachgestellt. Du hast drölfzigtausend Mods am Start, niemand sonst hat dieses Problem gemeldet, ich würde es gerne verstehen, aber ich werde nicht Mod für Mod durchgehen um zu schauen, ob es daran liegen könnte. Zu 90+% war es immer ein Modkonflikt, bzw eine doppel oder dreifachbelegung von Tasten oder noch schlimmer Controller oder Seitenkonsolen. Oder halt Spezialisierungen (wie autoload), die sich Tasten wegsnacken wenn sie an einem Vehicle attached sind.

EV hängt sich an Drivable+Enterable+Motorized ran und belegt dort seine Tasten.
Ebenfalls hänge ich mich in "updateVehiclePhysics" und "updateWheelsPhysics" rein. Wenn andere Mods nach EV ebenfalls diese Funktionen überschreiben und Einfluss nehmen, kann ich nichts machen.

**Comment by 112TEC-Chris** [comment]
ok, dann werde ich wohl mal mod für mod reinnehmen müssen und sehen, wodurch es passiert.

**Comment by ZhooL** [comment]
Was evtl. auch helfen könnte: In der FS22_EnhancedVehicle_Loader.lua den debug modus auf 2 stellen und einmal das Spiel starten, in das Fahrzeug, was nicht geht, und versuchen die Parkbremse zu lösen/setzen. Mit debug=2 sollte jede Aktion in EV eine Logmeldung erzeugen.

debug = 0 -- 0=0ff, 1=some, 2=everything, 3=madness

**Comment by 112TEC-Chris** [comment]
2022-04-26 16:43 -> FS22_EnhancedVehicle: onActionCall FS22_EnhancedVehicle_PARK, keyStatus: 1 (rootNode: 217828, typeName: car, typeDesc: Auto)
2022-04-26 16:43 -> FS22_EnhancedVehicle_Event: sendEvent(): 1: false, 2: false, 3: 1, 4: 0, 5: false, 6: false, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: false
2022-04-26 16:43 --> g_server:broadcastEvent()
2022-04-26 16:43 -> FS22_EnhancedVehicle: onActionCall FS22_EnhancedVehicle_PARK, keyStatus: 1 (rootNode: 217828, typeName: car, typeDesc: Auto)
2022-04-26 16:43 -> FS22_EnhancedVehicle_Event: sendEvent(): 1: false, 2: false, 3: 1, 4: 0, 5: false, 6: false, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: true
2022-04-26 16:43 --> g_server:broadcastEvent()

Also eine Reaktion kommt in der Log, aber es ändert sich nix auf dem Hud und die Feststellbremse wird auch nicht gelöst oder angezogen. Das gleiche gilt für die differentialsperren. Alles andere funktioniert anscheinend

**Comment by ZhooL** [comment]
Noch kurz nachgefragt: Single Player, MP (lokal) oder MP (dedi server)? Wenn MP, dann bräuchte man auch das Log vom Server um zu schauen, ob das geschickte Event zB umgesetzt wird.

**Comment by 112TEC-Chris** [comment]
single Player

**Comment by 112TEC-Chris** [comment]
Hast Du Discord? dann ist es einfacher

**Comment by ZhooL** [comment]
Ja, https://d.majo76.de
Wir können die Tage mal schauen, aber nicht heute oder morgen - keine Zeit ;-)

**Comment by ZhooL** [comment]
Problem gelöst - eine veraltete Version von UniversalAutoload war der Störenfried.
